# base-image
FROM openjdk:17-alpine
# 변수 설정 (빌드 파일 경로)
ARG JAR_FILE=build/libs/nuwa-monitoring-0.0.1-SNAPSHOT.jar
# 빌드 파일 컨테이너로 복사
COPY ${JAR_FILE} monitor.jar
# jar 파일 실행
ENTRYPOINT ["java", "-jar", "/monitor.jar"]