server:
  port: 8085
  servlet:
    context-path: /nuwa-admin

spring:
  boot:
    admin:
      ui:
        poll-timer:
          logfile: 60000

  security:
    user:
      name: ${ADMIN_ID}
      password: ${ADMIN_PASSWORD}

